#!/usr/bin/env python3
#
# SuperR's Kitchen v3.x - By SuperR.
#
# Do not edit this file unless you know what you are doing

import sys
import os
if os.name == 'posix':
    import termios
    import tty

import mainsrk


def getChar():
    def _ttyRead():
        fd = sys.stdin.fileno()
        oldSettings = termios.tcgetattr(fd)
        try:
            tty.setraw(fd)
            choice = sys.stdin.read(1)
        finally:
            termios.tcsetattr(fd, termios.TCSADRAIN, oldSettings)
        return choice

    return _ttyRead().lower()


print('Loading ...')

answer = ''

while answer != 'q':
    mainsrk.superr()
    if len(sys.argv) <= 1:
        print('\n\n\033[0m\033[32mPress "q" to Quit, or "r" to Restart\033[0m')
        answer = getChar()

        if answer == 'r':
            print('Restarting ...')
        else:
            answer = 'q'
    else:
        answer = 'q'

sys.exit()
